[package]
name = "goddard-propulsion"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Rocket engine and propulsion systems for the Goddard simulation framework"

[dependencies]
goddard-core = { workspace = true }
goddard-physics = { workspace = true } 