[package]
name = "goddard-propulsion"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Engine and propulsion systems for the Goddard rocket simulation framework"

[dependencies]
goddard-physics = { workspace = true } 